default_stages:
- commit
- push

files: (.+\.py|bin\/.+)

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: check-added-large-files
    args:
    - maxkb=1024
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: name-tests-test
    args:
    - --django

- repo: local
  hooks:
  - id: isort
    name: isort
    entry: poetry run isort
    language: system
    types:
    - python
    args:
    - --check-only

  - id: black
    name: black
    entry: poetry run black
    language: system
    require_serial: true
    types:
    - python
    args:
    - --check

  - id: flake8
    name: flake8
    entry: poetry run flake8
    language: system
    additional_dependencies: [flake8-bugbear]
    types:
    - python

