"""Add completed request column

Revision ID: 0651204e623d
Revises: a06108ef6642
Create Date: 2021-01-09 20:04:20.310457

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0651204e623d"
down_revision = "a06108ef6642"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("request", sa.Column("completed", sa.Boolean(), nullable=True))
    op.create_index(op.f("ix_request_completed"), "request", ["completed"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_request_completed"), table_name="request")
    op.drop_column("request", "completed")
    # ### end Alembic commands ###
