"""Requests table

Revision ID: 41f93c995f52
Revises: 
Create Date: 2020-12-26 19:42:31.191101

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "41f93c995f52"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "request",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("arg1", sa.Integer(), nullable=False),
        sa.Column("arg2", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_request_arg1"), "request", ["arg1"], unique=False)
    op.create_index(op.f("ix_request_arg2"), "request", ["arg2"], unique=False)
    op.create_index(op.f("ix_request_operation"), "request", ["operation"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_request_operation"), table_name="request")
    op.drop_index(op.f("ix_request_arg2"), table_name="request")
    op.drop_index(op.f("ix_request_arg1"), table_name="request")
    op.drop_table("request")
    # ### end Alembic commands ###
