"""Convert request arguments to bigint

Revision ID: 5ad84af62fe1
Revises: 41f93c995f52
Create Date: 2020-12-29 13:19:38.535156

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5ad84af62fe1"
down_revision = "41f93c995f52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("request", "arg1", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False)
    op.alter_column("request", "arg2", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("request", "arg2", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=True)
    op.alter_column("request", "arg1", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False)
    # ### end Alembic commands ###
