"""Add async columns

Revision ID: a06108ef6642
Revises: 5ad84af62fe1
Create Date: 2021-01-09 18:07:08.429600

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a06108ef6642"
down_revision = "5ad84af62fe1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("request", sa.Column("asynchronous", sa.Boolean(), nullable=True))
    op.add_column("request", sa.Column("email", sa.String(length=512), nullable=True))
    op.create_index(op.f("ix_request_asynchronous"), "request", ["asynchronous"], unique=False)
    op.create_index(op.f("ix_request_email"), "request", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_request_email"), table_name="request")
    op.drop_index(op.f("ix_request_asynchronous"), table_name="request")
    op.drop_column("request", "email")
    op.drop_column("request", "asynchronous")
    # ### end Alembic commands ###
