apiVersion: batch/v1
kind: Job
metadata:
  name: mathapi-migrate
  namespace: mathapi
  labels:
    name: mathapi
    type: migrate
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: mathapi-migrate
        image: localhost:32000/mathapi:latest
        command: ["flask", "db", "upgrade"]
        workingDir: /app/mathapi
        env:
          - name: FLASK_ENV
            value: "production"
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: mathapi-secrets
                key: database_uri
      restartPolicy: Never
  backoffLimit: 4
