apiVersion: v2
name: python
version: 2.0.2

dependencies:
- name: redis
  version: ~12.2.4
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: postgresql
  version: ~8.6.0
  repository: https://charts.helm.sh/stable
  condition: postgresql.enabled
- name: postgresql-backup
  version: ~0.0.1
  repository: https://storage.googleapis.com/t3n-helm-charts
  condition: postgresql-backup.enabled
- name: elasticsearch
  version: ~7.10.0
  repository: https://helm.elastic.co
  condition: kibana.enabled
- name: logstash
  version: ~7.10.0
  repository: https://helm.elastic.co
  condition: kibana.enabled
- name: kibana
  version: ~7.10.0
  repository: https://helm.elastic.co
  condition: kibana.enabled
- name: kube-prometheus-stack
  version: ~12.8.1
  repository: https://prometheus-community.github.io/helm-charts
  condition: monitoring.enabled
- name: sentry
  version: ~8.1.0
  repository: https://sentry-kubernetes.github.io/charts
  condition: monitoring.enabled
- name: jenkins
  version: ~3.0.12
  repository: https://charts.jenkins.io
  condition: jenkins.enabled


