apiVersion: v2
name: python
version: 2.0.2

dependencies:
- name: redis-ha
  version: ~3.11.0
  repository: https://charts.helm.sh/stable
  condition: redis.enabled
- name: postgresql
  version: ~8.6.0
  repository: https://charts.helm.sh/stable
  condition: postgresql.enabled
- name: postgresql-backup
  version: ~0.0.1
  repository: https://storage.googleapis.com/t3n-helm-charts
  condition: postgresql-backup.enabled
- name: elasticsearch
  version: ~7.10.0
  repository: https://helm.elastic.co
  condition: kibana.enabled
- name: logstash
  version: ~7.10.0
  repository: https://helm.elastic.co
  condition: kibana.enabled
- name: kibana
  version: ~7.10.0
  repository: https://helm.elastic.co
  condition: kibana.enabled


